name: binance_pay
description: A Flutter package for integrating Binance Pay API into your mobile applications, enabling users to make payments with ease.
version: 0.0.3
homepage: https://github.com/MarsadMaqsood/binance_pay

environment:
  sdk: ^3.1.0

dependencies:
  convert: ^3.1.1
  crypto: ^3.0.3
  http: ^1.2.1

dev_dependencies:
  test: ^1.16.0
  lints: ^4.0.0

topics:
 - binance
 - payment
 - binance-pay
